### ISSUE TITLE
Script isn't working

### ISSUE THREAD

**Issue by Tomozxx** [ffluxxus/r6-norecoil#1]
I followed all the steps and the recoil isnt going down

**Comment by ojmb4** [comment]
Same here this script isnt working none of the g hub ones are?

**Comment by ffluxxus** [comment]
Script still works for me. Make sure you have your capslock key toggled as that is the way it activates.

**Comment by ffluxxus** [comment]
Correction. After the Skopos update the new toggle key is the NumLock key, or NumLk.
